@@startmindmap pojecia
!theme _none_
<style>
mindmapDiagram {
    '/colors https://colordesigner.io /'
  .green1 {
    BackgroundColor #3ba040
  }
  .green2 {
    BackgroundColor #4ebe54
  }
  .green3 {
    BackgroundColor #71cb76
  }
  .green4 {
    BackgroundColor #c1e27e
  }
  .green5 {
    BackgroundColor #b8e5ba
  }
  .rose {
    BackgroundColor LightPink
  }
  .blue1{
    BackgroundColor #328de7
  }
  .blue2{
    BackgroundColor #5ba4eb
  }
  .blue3{
    BackgroundColor #84bbf0
  }    
  .blue4{
    BackgroundColor #add1f5
  } 
  .blue5{
    BackgroundColor #aae1fe
  } 
  .blue {
    BackgroundColor lightblue
  }
  .purple1 {
    BackgroundColor #a269c6
  }
  .purple2 {
    BackgroundColor #9524e0
  }
  .purple3 {
    BackgroundColor #aa50e6
  }
  .purple4 {
    BackgroundColor #bf7cec
  }
  .purple5 {
    BackgroundColor #ead3f9
  }
  .yellow1 {
    BackgroundColor #F1C40F
  }
  .yellow2 {
    BackgroundColor #F4D03F
  }
  .turquoise1 {
    BackgroundColor #1ABC9C
  }
  .turquoise2 {
    BackgroundColor #48C9B0
  }
  .lightblue1 {
    BackgroundColor #5DADE2
  }
  .lightblue2 {
    BackgroundColor #85C1E9
  }
  .orange1 {
    BackgroundColor #F39C12
  }
  .orange2 {
    BackgroundColor #F5B041
  }
  .orange3{
    BackgroundColor #F8C471 
  }
  .orange4{
    BackgroundColor #FAD7A0 
  }
  .brownred1 {
    BackgroundColor #DC7633
  }
  .brownred2 {
    BackgroundColor #E59866
  }
  .coralred1 {
    BackgroundColor #EC7063
  }
  .coralred2 {
    BackgroundColor #F1948A
  }
  .slateGrey {
      BackgroundColor LightSlateGray
  }
  .violet {
      BackgroundColor #b385d0
  }
  .oliveGreen{
    BackgroundColor #afb83b
  }
  .skyBlue{
    BackgroundColor #14aaf5
  }
  .mintGreen{
    BackgroundColor #6accbc
  }
  .red {
    BackgroundColor #FF3D3D
  }
  .bananaYellow {
    BackgroundColor #E6E600
  }
  .brown {
    BackgroundColor #B87D4B
  }

}
</style>

+ Sklep Zoologiczny

++ Promocje <<red>>

++ **"General"**
+++ Żywność
++++ Karmy
+++++ Karma Mokra
+++++ Karma sucha
+++++ Marki
+++++ Smakołyki

++ Psy <<blue1>>

+++ Akcesoria <<blue3>>
++++ Kagańce <<blue3>>
++++ Smycze <<blue3>>
++++ Miski <<blue3>>
++++ Legowiska <<blue3>>
+++++_ Miski na wode <<blue3>>
+++++_ Miski do jedzenia <<blue3>>

+++ Trening  <<blue4>>
++++ Smycze <<blue4>>
++++ Maty <<blue4>>
++++ Gwizdki <<blue4>>
++++ Obroże <<blue4>>
++++ Dzwiekowe akcesoria <<blue4>>

+++ Zabawki <<blue5>>
++++ Piłki <<blue5>>
++++ Kongi <<blue5>>
++++ pluszowe <<blue5>>
++++ Gryzaki <<blue5>>
+++++ Drewniane <<blue5>>
+++++ Gumowe <<blue5>>

+++ Szarpaki <<blue3>>
++++ Gumowe <<blue3>>
++++ Materiałowe <<blue3>>
++++ skórzane <<blue3>>
++++ mieszane <<blue3>>
+++ Zdrowie <<blue4>>

++++ Pęsety na kleszcze <<blue4>>
++++ Preparaty na pchły <<blue4>>
++++ Obroże na kleszcze <<blue4>>
++++ Szampony <<blue4>>
++++ Grzebienie <<blue4>>
++++ Szczotki do zębów <<blue4>>

++ Koty <<green1>>

+++ Zabawki <<green2>>
++++ Elektroniczne <<green2>>
++++ Wędki <<green2>>
++++ Piłki <<green2>>

+++ Akcesoria <<green3>>
++++ Drapaki <<green3>>
++++ Legowiska <<green3>>
++++ Kuwety <<green3>>
++++ Transportery <<green3>>
++++ Miski <<green3>>
++++ Obroże <<green3>>
++++ Szelki <<green3>>

+++ Zdrowie <<green4>>
++++ Pęsety na kleszcze <<green4>>
++++ Obroże na kleszcze <<green4>>
++++ Preparaty na pchły <<green4>>
++++ Szampony <<green4>>
++++ Grzebienie <<green4>>
++++ Szczotki do zębów <<green4>>

++ **Małe ssaki** <<purple1>>

+++ Karmy <<purple3>>
++++ Karma dla chomika <<purple3>>
++++ Karma dla myszy <<purple3>>
++++ Karma dla królika <<purple3>>
++++ Karma dla szczura <<purple3>>
++++ Karma dla fretki <<purple3>>
++++ Karma dla świnki morskiej <<purple3>>

+++ Akcesoria <<purple4>>
++++ Klatki <<purple4>>
++++ Miski <<purple4>>
++++ Poidełka <<purple4>>
++++ Transportery <<purple4>>
++++ Kołowrotki <<purple4>>
++++ Domki dla gryzoni <<purple4>>

+++ Zdrowie <<purple5>>
++++ Witaminy dla małych ssaków <<purple5>>
++++ Podkłady <<purple5>>
++++ Pielęgnacja małych ssaków <<purple5>>



-- Moje Konto <<yellow1>>
--- Koszyk  <<yellow2>>
--- Zamówienia <<yellow2>>
--- Lista życzeń <<yellow2>>

-- Kontakt <<coralred1>>
--- Znajdz Sklep <<coralred2>>
--- Formularz kontaktowy <<coralred2>>
--- Telefoniczny <<coralred2>>
--- Mailowy <<coralred2>>

-- Pomoc <<brownred1>>
--- Dostawa <<brownred2>>
--- Wymiana i zwroty <<brownred2>>
--- Płatności <<brownred2>>
--- Zamówienia online <<brownred2>>

-- Polityka <<lightblue1>>
--- Regulamin <<lightblue2>>
--- Polityka prywatności <<lightblue2>>
--- Polityka cookies <<lightblue2>>

-- Newsletter <<mintGreen>>

-- 0 nas <<orange3>>
--- Działalność <<orange4>>
--- Zespół <<orange4>>
--- Sklepy stacjonarne  <<orange4>>


-- Poradnik <<orange1>>
--- Akcesoria  <<orange2>>
--- Porady <<orange2>>
--- Rasy <<orange2>>
--- Zdrowie <<orange2>>
--- Żywienie <<orange2>>



@@endmindmap